import type { PerformanceInfo } from "./types";

export const INITIAL_PERFORMANCE_INFO: PerformanceInfo = {
  applicantCompanyName: "",
  applicantBusinessRegistrationNumber: "",
  applicantContactName: "",
  applicantContactPhone: "",
  operationsResponsible: { name: "", title: "", phone: "" },
  safetyResponsible: { name: "", title: "", phone: "" },
  pastPerformances: [],
  eventName: "",
  artist: "",
  organizer: "",
  eventScale: "",
  eventTypes: [],
  ageRating: null,
  ageLimitDetail: "",
  stageTypes: [],
  seatingTypes: [],
  retractableSeatUse: null,
  teardownCompletionTime: "",
  ticketOpenExpectedDate: "",
  expectedPaidSalesRate: 0,
  ancillaryBusinessPlans: [],
  castContractStatus: null,
  foreignArtistNotes: "",
  sensitiveInfoMaskingAcknowledged: false,
  safetyPledgeSigned: false,
};
