"use client";
import { useState } from "react";
import { ReportTimeTabs } from "./ReportTimeTabs";
import { ReportTrendChart } from "./ReportTrendChart";
import { ReportBars } from "./ReportBars";
import s from "./AdminReportPreview.module.css";
const num=(n:number)=>n.toLocaleString("ko-KR");
function StatCard({label,value,sub}:{label:string;value:string;sub?:string}){return <article className={s.card}><p>{label}</p><strong className={s.value}>{value}</strong>{sub&&<small>{sub}</small>}</article>;}
function BreakdownTable({title,rows,showTotal}:{title:string;rows:{key:string;label:string;count:number;total:number}[];showTotal?:boolean}){return <section className={s.card}><h2>{title}</h2><ReportBars rows={rows.map(r=>({label:r.label,value:r.count,detail:showTotal?`${num(r.total)}원`:undefined}))}/></section>;}
const VENUE_TABS=[{key:"all",label:"전체"},{key:"arena",label:"아레나"},{key:"medium-hall",label:"중형공연장"}];
export function OriginalReportPreview({tab}:{tab:"퍼널"|"매출"|"모니터링"}){
 const [mode,setMode]=useState("day");
 const [venueTab,setVenueTab]=useState("all");
 const [range,setRange]=useState(["2026-09-26","2026-10-02"]);
 const inRange=range[0]<="2026-10-02"&&range[1]>="2026-10-02";
 const venueLabel=VENUE_TABS.find(t=>t.key===venueTab)!.label;
 const scale=venueTab==="all"?3:venueTab==="arena"?2:1;
 const steps=[ ["방문",2,"명","브라우저 기준 순방문자"],["가입 화면",0,"명","/register 를 연 방문자"],["가입 완료",1,"명","기간 내 생성된 신청자 계정"],["회사 승인",0,"곳","운영자 승인을 받은 회사"],["대관신청 클릭",1,"명","/apply 로 가는 버튼을 누른 방문자"],["위저드 진입",1,"명","로그인 상태로 신청 화면에 들어온 회원"],["신청서 제출",0,"건","실제로 접수된 대관 신청서"] ] as const;
 const funnel=steps.map(([label,count,unit,hint],i)=>({key:label,label,count:inRange?count:0,unit,hint,rate:!inRange||i===0||steps[i-1][1]===0?null:Math.round(count/steps[i-1][1]*100)}));
 const stalled: {companyId:string;companyName:string;memberCount:number;reached:string;lastSeenAt:string|null;idleDays:number}[]=[];
 const ops={pendingReviews:3,pendingCompanies:2,openInquiries:1,oldestInquiryDays:4,adminsWithoutPhone:1,messagesSent:inRange?198:0,messagesFailed:inRange?2:0,messageFailureTop:inRange?[{templateCode:"DEMO_NOTICE",reason:"수신번호 오류 (예시)",count:2}]:[]};
 const aws={available:true,reason:"예시 데이터",runningTasks:3,cpuAvg:24,cpuMax:48,responseTime:0.182,serverErrors:0,clientErrors:4,blockedRequests:12,allowedRequests:9600,dbCpu:18,dbConnections:8};
 const breakdown=(labels:string[],counts:number[])=>labels.map((label,i)=>({key:label,label,count:counts[i],total:counts[i]*100000000}));
 const monthly=Array.from({length:6},(_,i)=>({key:`2026-${String(i+5).padStart(2,"0")}`,label:`2026.${String(i+5).padStart(2,"0")}`,count:scale,total:scale*100000000}));
 const stats={totalQuotes:scale*6,newThisMonth:scale,pendingReview:scale,contractedCount:scale*2,contractedTotal:scale*200000000,settledCount:scale,reviewBreakdown:breakdown(["승인","보류","거절"],[scale*3,scale,scale]),venueBreakdown:breakdown(venueTab==="all"?["아레나","중형공연장"]:[venueLabel],venueTab==="all"?[12,6]:[scale*6]),companyBreakdown:breakdown(["승인 대기","승인 완료","거절","정지"],[2,8,1,0]),monthly};
 const revenue={submittedCount:scale*6,submittedTotal:scale*600000000,contractedCount:scale*2,contractedTotal:scale*200000000,settledTotal:scale*100000000,settledCount:scale,pendingSettlementTotal:scale*100000000,pendingSettlementCount:scale,addendumTotal:0,monthly:monthly.map((m,i)=>({...m,submittedCount:scale,submittedTotal:m.total,contractedCount:i>=4?scale:0,contractedTotal:i>=4?scale*100000000:0,settledTotal:i===5?scale*100000000:0}))};
 return <div className={s.originalContent}>
 {tab!=="매출"&&<ReportTimeTabs hourly={tab==="모니터링"} from={range[0]} to={range[1]} mode={mode} onChange={(next,from,to)=>{setMode(next);setRange([from,to]);}}/>}
 {tab==="퍼널"?<><section className={s.funnelSection}><h2>신청 퍼널</h2><ReportBars rows={funnel.map(r=>({label:r.label,value:r.count,unit:r.unit,detail:`${r.hint} · 직전 대비 ${r.rate===null?'—':r.rate+'%'}`}))}/><p className={s.note}>단계마다 세는 단위가 달라 통과율은 흐름을 보는 용도로 읽어 주세요.</p></section><section className={s.funnelSection}><h2>승인 후 아직 신청서를 내지 않은 회사</h2><ReportBars rows={stalled.map(r=>({label:r.companyName,value:r.idleDays,unit:'일',detail:r.reached}))}/></section></>:tab==="모니터링"?<>
 <section className={s.funnelSection}><h2>지금 처리해야 할 것</h2><p className={s.note}>기간과 무관한 현재 상태입니다.</p><div className={s.signupMetrics}><StatCard label="심사 대기 신청서" value={`${ops.pendingReviews}건`}/><StatCard label="가입 승인 대기" value={`${ops.pendingCompanies}곳`}/><StatCard label="미답변 문의" value={`${ops.openInquiries}건`} sub={`가장 오래된 건 ${ops.oldestInquiryDays}일 경과`}/><StatCard label="휴대폰 없는 운영자" value={`${ops.adminsWithoutPhone}명`}/></div></section>
 <section className={s.funnelSection}><h2>알림톡·문자 발송</h2><div className={s.metrics}><StatCard label="성공" value={`${ops.messagesSent}건`}/><StatCard label="실패" value={`${ops.messagesFailed}건`}/><StatCard label="성공률" value={inRange?'99%':'—'}/></div><ReportTrendChart points={inRange?mode==='month'?[{label:'2026-09',values:[137,2]},{label:'2026-10',values:[61,0]}]:mode==='week'?[{label:'2026-09-21',values:[40,0]},{label:'2026-09-28',values:[158,2]}]:[12,28,14,47,36,41,20].map((sent,i)=>({label:mode==='hour'?`2026-10-02 ${String(i+8).padStart(2,'0')}:00`:i===6?'2026-10-02':i===5?'2026-10-01':`2026-09-${26+i}`,values:[sent,i===3?2:0]})):[]} series={[{label:'성공',unit:'건',color:'#337a9a'},{label:'실패',unit:'건',color:'#bf4e49'}]}/><h3>실패 사유</h3><ReportBars rows={ops.messageFailureTop.map(r=>({label:r.templateCode,value:r.count,detail:r.reason}))}/></section>
 <section className={s.funnelSection}><h2>서버 · 차단</h2><div className={s.signupMetrics}><StatCard label="가동 중인 서버" value={`${aws.runningTasks}대`}/><StatCard label="CPU" value={`${aws.cpuAvg}%`} sub={`최고 ${aws.cpuMax}%`}/><StatCard label="평균 응답시간" value={`${aws.responseTime*1000}ms`}/><StatCard label="서버 오류" value={`${aws.serverErrors}건`}/></div><ReportBars rows={[{label:'서버 CPU',value:aws.cpuAvg,unit:'%'},{label:'DB CPU',value:aws.dbCpu,unit:'%'}]}/><ReportBars rows={[{label:'방화벽 차단',value:aws.blockedRequests},{label:'정상 통과',value:aws.allowedRequests},{label:'요청 오류',value:aws.clientErrors}]}/><p className={s.note}>디자인 검토용 예시 데이터입니다. DB 접속 {aws.dbConnections}개.</p></section>
 </>:<>
 <nav className={s.segmented} aria-label="공간 탭">{VENUE_TABS.map(t=><button type="button" aria-pressed={venueTab===t.key} key={t.key} onClick={()=>setVenueTab(t.key)}>{t.label}</button>)}</nav>
 <section className={s.funnelSection}><h2>공간별 신청 현황</h2><div className={s.signupMetrics}><StatCard label="누적 신청 건수" value={`${stats.totalQuotes}건`}/><StatCard label="이번 달 신규 신청" value={`${stats.newThisMonth}건`}/><StatCard label="심사 대기" value={`${stats.pendingReview}건`}/><StatCard label="계약 확정" value={`${stats.contractedCount}건`} sub={`계약금액 ${num(stats.contractedTotal)}원`}/></div></section>
 <section className="grid gap-4 lg:grid-cols-2"><BreakdownTable title="심사 결과 분포" rows={stats.reviewBreakdown}/><BreakdownTable title="공간별 신청 현황" rows={stats.venueBreakdown} showTotal/><BreakdownTable title="법인회원 승인 현황" rows={stats.companyBreakdown}/><section className={s.card}><h2>정산 완료</h2><strong className={s.value}>{stats.settledCount}건</strong></section></section>
 <section className={s.funnelSection}><h2>매출 · {venueLabel}</h2><div className={s.signupMetrics}><StatCard label="접수 건수" value={`${revenue.submittedCount}건`} sub={`견적 ${num(revenue.submittedTotal)}원`}/><StatCard label="계약 건수" value={`${revenue.contractedCount}건`} sub={`계약금액 ${num(revenue.contractedTotal)}원`}/><StatCard label="총 확정 매출" value={`${num(revenue.settledTotal)}원`}/><StatCard label="정산 예정" value={`${num(revenue.pendingSettlementTotal)}원`}/></div></section>
 <section className={s.funnelSection}><h2>월별 매출 추이 (최근 6개월)</h2><ReportTrendChart points={revenue.monthly.map(m=>({label:m.label,values:[m.submittedTotal,m.contractedTotal,m.settledTotal],detail:`접수 ${m.submittedCount}건 · 계약 ${m.contractedCount}건`}))} series={[{label:'견적 금액',unit:'원',color:'#999999'},{label:'계약금액',unit:'원',color:'#337a9a'},{label:'확정 매출',unit:'원',color:'#222222'}]}/></section>
 <section className={s.funnelSection}><h2>월별 신청 추이 (최근 6개월)</h2><ReportTrendChart points={stats.monthly.map(m=>({label:m.label,values:[m.count],detail:`대관료 합계 ${num(m.total)}원`}))} series={[{label:'신청 건수',unit:'건',color:'#337a9a'}]}/></section>
 </>}</div>;
}
